data_analytics_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('departments/', views.departments, name='departments'),
    path('departments/<slug:slug>/', views.department, name='department'),
    path('programs/', views.programs, name='programs'),
    path('programs/<str:id>/<slug:slug>/', views.program_detail, name='program_detail'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>
        {% block title %}NITDA{% endblock %}
    </title>
	<link rel="icon" type="image/png" href="{% static 'assets/img/logo.png' %}">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'>
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="../css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
	<link rel="stylesheet" href="{% static 'assets/css/ready.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/demo.css' %}">
	<script scr="https://cdn.plot.ly/plotly-latest.min.js"></script>
	{% block style %}
	{% endblock %}
</head>
<body>
	<div class="wrapper">
		<div class="main-header">
			<div class="logo-header">
				<a href="{% url 'main:index' %}" class="logo">
					NITDA
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
			</div>
			<nav class="navbar navbar-header navbar-expand-lg">
				<div class="container-fluid">
					<h3>Welcome To NITDA</h3>
					</div>
				</nav>
			</div>
			<div class="sidebar">
				<div class="scrollbar-inner sidebar-wrapper">

					<ul class="nav">
						<li class="nav-item active">
							<a href="{% url 'main:index' %}">
								<i class="la la-home"></i>
								<p>Home</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'main:departments' %}">
								<i class="la la-table"></i>
								<p>Departments</p>
								<span class="badge badge-count">{{ total_departments }}</span>
							</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'main:programs' %}">
								<i class="la la-keyboard-o"></i>
								<p>Programs</p>
								<span class="badge badge-count">{{ total_programs }}</span>
							</a>
						</li>
<!--						<li class="nav-item">-->
<!--							<a href="tables.html">-->
<!--								<i class="la la-th"></i>-->
<!--								<p>Tables</p>-->
<!--								<span class="badge badge-count">6</span>-->
<!--							</a>-->
<!--						</li>-->
<!--						<li class="nav-item">-->
<!--							<a href="notifications.html">-->
<!--								<i class="la la-bell"></i>-->
<!--								<p>Notifications</p>-->
<!--								<span class="badge badge-success">3</span>-->
<!--							</a>-->
<!--						</li>-->
<!--						<li class="nav-item">-->
<!--							<a href="typography.html">-->
<!--								<i class="la la-font"></i>-->
<!--								<p>Typography</p>-->
<!--								<span class="badge badge-danger">25</span>-->
<!--							</a>-->
<!--						</li>-->
<!--						<li class="nav-item">-->
<!--							<a href="icons.html">-->
<!--								<i class="la la-fonticons"></i>-->
<!--								<p>Icons</p>-->
<!--							</a>-->
<!--						</li>-->
					</ul>
				</div>
			</div>
			<div class="main-panel">
				{% block content_block %}


				{% endblock %}
				<footer class="footer">
					<div class="container-fluid">
						<nav class="pull-left">
							<ul class="nav">
								<li class="nav-item">
									<a class="nav-link" href="https://nitda.gov.ng">
										NITDA
									</a>
								</li>
							</ul>
						</nav>
						<div class="copyright ml-auto">
							© <script>document.write(new Date().getFullYear());</script>
						</div>
					</div>
				</footer>
			</div>
		</div>

</body>
{% block script %}
<script src="{% static 'assets/js/core/jquery.3.2.1.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/js/core/popper.min.js' %}"></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/chartist/chartist.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/chartist/plugin/chartist-plugin-tooltip.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/jquery-mapael/jquery.mapael.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/jquery-mapael/maps/world_countries.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>
<script src="{% static 'assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'assets/js/ready.min.js' %}"></script>
<script src="{% static 'assets/js/demo.js' %}"></script>
{% endblock %}
</html>